### ISSUE TITLE
AP computation is incorrect

### ISSUE THREAD

**Issue by david-fisher** [nathancday/rank-algo-app#1]
AP is generally computed as the sum of p(r) for each rank r where the document is judged relevant, divided by the total number of relevant documents, using binary judgments. Multi-valued judgments are typically binned. The value computed by the code when running the app should be 1.0 for the only relevant document in the 1st position of the list, and should not change as the rank increases from 1-10. 

[https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision](https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Average_precision)

**Comment by nathancday** [comment]
Thanks for raising this issue David, I'm working on a long over-due PR to fix this now.
